In [4]:
import numpy as np
import pandas as pd
import random

In [1]:
def create_grid(width, height):
    grid = [[0 for x in range(width)] for y in range(height)]
    # Randomly choose a cell in the top left quadrant
    top_left_x = random.randint(0, width // 2)
    top_left_y = random.randint(0, height // 2)
    # Randomly choose a cell in the bottom right quadrant
    bot_right_x = random.randint(width // 2, width - 1)
    bot_right_y = random.randint(height // 2, height - 1)
    
    # Create a gradient of values between the two cells
    for x in range(top_left_x, bot_right_x + 1):
        for y in range(top_left_y, bot_right_y + 1):
            value = (x - top_left_x) / (bot_right_x - top_left_x)
            grid[y][x] = value
            
    return grid

In [5]:
create_grid(10,10)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0.0, 0.25, 0.5, 0.75, 1.0],
 [0, 0, 0, 0, 0, 0.0, 0.25, 0.5, 0.75, 1.0],
 [0, 0, 0, 0, 0, 0.0, 0.25, 0.5, 0.75, 1.0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [7]:
#import necessary packages
import random
import numpy

#set grid size
rows = 10
cols = 10

#create empty grid
grid = numpy.zeros((rows, cols))

#function to randomly drop dirt onto grid
def drop_dirt(grid):
    x = random.randint(0, rows - 1)
    y = random.randint(0, cols - 1)
    grid[x, y] += 1

#function to check if dirt is overflowing from its current location
def check_overflow(grid):
    for x in range(rows):
        for y in range(cols):
            #check if the current square has more than 4 dirt
            if grid[x, y] > 4:
                #check in all 8 directions for eligible squares
                for dx in [-1, 0, 1]:
                    for dy in [-1, 0, 1]:
                        if 0<=x+dx<rows and 0<=y+dy<cols and grid[x+dx, y+dy] < grid[x, y]:
                            #if current square is at least 5, distribute 4 dirt to eligible squares
                            if grid[x, y] >= 5:
                                grid[x+dx, y+dy] += 4
                                grid[x, y] -= 4
                            #stop redistributing once the initial square is within 1 difference of one of its neighbors
                            elif grid[x+dx, y+dy] >= grid[x, y] - 1:
                                break

#run the simulation
for i in range(1000):
    drop_dirt(grid)
    check_overflow(grid)

#print out the final grid
print(grid)

[[35. 34. 30. 32. 30. 26. 27. 29. 27. 25.]
 [26. 24. 24. 25. 20. 22. 22. 23. 24. 20.]
 [22. 19. 18. 17. 15. 15. 16. 15. 17. 12.]
 [18. 13. 12. 11. 11. 10. 12.  8.  6.  8.]
 [12. 12.  9.  6.  8.  8.  5.  2.  2.  1.]
 [ 7.  2.  6.  6.  2.  2.  3.  1.  4.  3.]
 [ 4.  1.  1.  1.  4.  4.  2.  4.  2.  2.]
 [ 4.  2.  1.  3.  2.  1.  3.  3.  2.  2.]
 [ 4.  2.  2.  1.  4.  3.  2.  4.  1.  4.]
 [ 2.  2.  2.  3.  1.  4.  4.  1.  3.  2.]]


In [19]:
def traverseGrid(grid):
    #initializing counts for directions
    northCount = 1
    southCount = 1
    eastCount = 1
    westCount = 1
    
    #get size of grid
    rows = len(grid)
    cols = len(grid[0])
    
    #start at random location in grid
    x = random.randint(0, rows - 1)
    y = random.randint(0, cols - 1)
    
    #keep track of total sum of values
    totalSum = 0
    
    #dictionary for direction table of weighted sums
    directionTable = {
        'North': 0,
        'South': 0,
        'East': 0,
        'West': 0
    }
    
    counts = 0
    #loop until max value is found
    while True:
        counts += 1
        #check if current position is max value
        if grid[x][y] == max(grid.flatten()):
            #return final coordinates, value, and direction table
            return (x, y, grid[x][y], directionTable,counts)
        
        #calculate average sum of values
        averageSum = totalSum / (northCount + southCount + eastCount + westCount)
        
        #update direction counts
        if grid[x][y] > averageSum:
            if x > 0:
                northCount += 1
            if x < rows - 1:
                southCount += 1
            if y > 0:
                westCount += 1
            if y < cols - 1:
                eastCount += 1
        
        #calculate probabilities for each direction
        if x > 0:
            northProb = northCount / (northCount + southCount + eastCount + westCount)
        else:
            northProb = 0
        if x < rows - 1:
            southProb = southCount / (northCount + southCount + eastCount + westCount)
        else:
            southProb = 0
        if y < cols - 1:
            eastProb = eastCount / (northCount + southCount + eastCount + westCount)
        else:
            eastProb = 0
        if y > 0:
            westProb = westCount / (northCount + southCount + eastCount + westCount)
        else:
            westProb = 0
        
        #update direction table
        directionTable['North'] = northProb
        directionTable['South'] = southProb
        directionTable['East'] = eastProb
        directionTable['West'] = westProb
        
        #generate random number between 0 and 1
        rand = random.random()
        
        #check which direction to go
        if rand < northProb:
            x -= 1
        elif rand < northProb + southProb:
            x += 1
        elif rand < northProb + southProb + eastProb:
            y += 1
        else:
            y -= 1
        
        #update total sum
        totalSum += grid[x][y]

In [20]:
traverseGrid(grid)

(0, 0, 35.0, {'North': 0, 'South': 0, 'East': 0, 'West': 0}, 1)